name: build
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        strategy:
            matrix:
                include:
                    - os: windows-latest
                      command: package-win32-x64
                    - os: ubuntu-latest
                      command: package-linux-x64
                    - os: macos-latest
                      command: package-darwin-x64
                    - os: ubuntu-latest
                      command: package-web
                    - os: ubuntu-latest
                      command: package-universal
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
            - name: Install dependencies
              run: npm ci
            - name: Generate Antlr lexer
              run: npx antlr4ts -o "../src/_generated" "AntlrGlslLexer.g4"
              working-directory: ./syntaxes
            - name: Generate Antlr parser
              run: npx antlr4ts -o "../src/_generated" -no-listener -visitor "AntlrGlslParser.g4"
              working-directory: ./syntaxes
            - name: ESLint
              run: npm run eslint
            - name: Markdownlint
              run: npm run markdownlint
            - name: Prettier lint
              run: npm run prettier-lint
            - name: Build in production mode
              run: npm run build-production
            - name: Package
              run: npm run ${{ matrix.command }}
